os: Windows Server 2012 R2
platform:
  - x64

branches:
    only:
        - master
        
# Not a .NET Project or Solution so prevent appveyor from complaining.  Were just utilizing it for automation.  Not
# Building .net application
build: off
        
install:
    # Print O/S Information to build log
    - ps: 'Get-CimInstance win32_operatingsystem -Property Caption, OSArchitecture, Version | fl Caption, OSArchitecture, Version'
    - ps: $PSVersionTable
    # Install latest version of the chefdk
    - ps: iex (irm https://omnitruck.chef.io/install.ps1); Install-Project -Project chefdk -channel current
